### ISSUE TITLE
about transparent_proxy.sh on QUIC UDP package proxy

### ISSUE THREAD

**Issue by cattyhouse** [kaaass/manjaro-settings#1]
Have you tried enabling QUIC on Google Chrome `chrome://flags/#enable-quic`, and then test any youtube 4k video for the QUIC traffic? or you can run a QUIC test to see if the transparent proxy works with QUIC UDP traffice here? https://quic.nginx.org/quic.html

**Comment by kaaass** [comment]
Yes, I could confirm response header `client-protocol: quic
` presented (while the actual protocol is `h3-29`) in my youtube video traffic. Also, https://cloudflare-quic.com/ shows that HTTP/3 are available. It seems like that the latest chrome prefers HTTP/3 than HTTP/2 + QUIC, which makes sense to me but will prevent you from passing QUIC only tests.

Additionally, vivaldi browser (5.1.2567.73) could pass https://quic.nginx.org/quic.html .

**Comment by cattyhouse** [comment]
I thought it was due to improper UDP proxy implement of the tools being used, but actually it was due to Youtube QUIC UDP traffic is much bigger than other UDP traffic (e.g. DNS UDP). if you turn on verbose log on proxy client at local or proxy server at remote, you'll see that there is something like _**several hundreds**_ UDP packages with size of 1250 bytes **_per second_**, that is the cause of slow 4k video loading performance.

**Comment by kaaass** [comment]
Seems like it's an upstream problem and no further talk is needed, so I'll close this issue.

Feel free to reopen it if you find it necessary.
